[package]
name = "kailivev2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = "4.3.0"
serde_json = "1.0.96"
tokio = "1.28.2"
